<a href="https://colab.research.google.com/github/CakeNuthep/Pytorch_Learning/blob/main/PytorchBegin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# การติดตั้ง

In [1]:
import torch

In [2]:
print(torch.__version__)

1.7.0+cu101


In [3]:
torch.cuda.is_available()

True

# การใช้ง่าน Tensor ใน Torch

In [7]:
x = torch.rand(3,4,dtype = torch.float32)
dtype = print(x)

tensor([[0.7731, 0.2842, 0.2401, 0.1534],
        [0.5628, 0.3804, 0.7206, 0.4625],
        [0.1266, 0.8425, 0.9594, 0.0886]])


In [8]:
x = torch.zeros(5,3, dtype= torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = x.new_ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.tensor([4.123,3])
print(x)

tensor([4.1230, 3.0000])


In [11]:
x = torch.randn_like(x, dtype=torch.float32)   #result has the same size
print(x)

tensor([-0.0630, -0.1950])


In [12]:
x = torch.Tensor(5,3).fill_(7)
print(x)

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])


In [14]:
x = torch.Tensor(5,3).fill_(7).type(torch.int)
print(x)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]], dtype=torch.int32)


In [15]:
torch.manual_seed(1)
x = torch.randn(5,3)
print(x)

tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661],
        [-1.5228,  0.3817, -1.0276],
        [-0.5631, -0.8923, -0.0583],
        [-0.1955, -0.9656,  0.4224]])


# การแปลงไปมาระหว่าง numpy กับ Tensor

In [ ]:
import numpy as np
a = np.array([1.,3.])
t = torch.from_numpy(a)
print(t) # ได้ tensor([1.,3.])
print(a) # ได้ [ 1.,3.]
t += 1
print(t) # ได้ tensor([2.,4.])
print(a) # ได้ [ 2.,4.]

tensor([1., 3.], dtype=torch.float64)
[1. 3.]
tensor([2., 4.], dtype=torch.float64)
[2. 4.]


In [ ]:
a = np.array([1.,3.])
t = torch.Tensor(a)
print(t) # ได้ tensor([1.,3.])
print(a) # ได้ [ 1.,3.]
t += 1
print(t) # ได้ tensor([2.,4.])
print(a) # ได้ [ 1.,3.]

tensor([1., 3.])
[1. 3.]
tensor([2., 4.])
[1. 3.]


In [ ]:
t = torch.Tensor([2,3])
b = t.numpy()
print(b) # ได้ [ 2.,3.]
b += 1
print(b) # ได้ [ 3.,4.]
print(t) # ได้ tensor([3.,4.], dtype=torch.float64)

[2. 3.]
[3. 4.]
tensor([3., 4.])


In [ ]:
t = torch.Tensor([2,3])
b = np.array(t.data)
b += 1
print(b) # ได้ [ 3.  4.]
print(t) # ได้ tensor([2., 3.])

[3. 4.]
tensor([2., 3.])


# การคำนวณ

In [ ]:
t1 = torch.ones(5,3)
print("t1")
print(t1)

t2 = torch.zeros(5,3)
print("t2")
print(t2)

print("t1+t2")
print(t1+t2)

print("t1-t2")
print(t1-t2)

print("t1*t2")
print(t1*t2)

t1
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t2
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
t1+t2
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t1-t2
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t1*t2
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## Dot Product

In [ ]:
t1 = torch.ones(5,3)
t2 = torch.Tensor(3,5).fill_(2)
print("t1")
print(t1)

print("t2")
print(t2)

print("dot product")
print(torch.matmul(t1,t2))

t1
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t2
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
dot product
tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])


In [ ]:
t = torch.ones(5,3)
print(t.mean()) # ได้ tensor(1.)
print(t.sum()) # ได้ tensor(15.)
print(t.std()) # ได้ tensor(0.)
print(t.max())
print(t.min())

tensor(1.)
tensor(15.)
tensor(0.)
tensor(1.)
tensor(1.)


# การเปลี่ยนรูปร่าง

In [ ]:
t = torch.ones(5,3)
print(t)
print(t.view(1,15))
print(t.view(3,5))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
print(t.flatten())

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


# การใช้ GPU

In [ ]:
device = torch.device("cuda")
t = torch.ones(5,3).to(device)

# Neural Network